#!/bin/sh

set -e
top_srcdir=$(dirname $0)"/../.."
. $top_srcdir/src/tests/funcs.sh

expected_tests=8

start
add_cars
add_node p1 \
"FROM test/cars SELECT
   min horsepower,
   max (horsepower),
   sum u32(horsepower) as sum_horsepower,
   avg horsepower,
   first ((horsepower)),
   last horsepower,
   10th percentile horsepower,
   95th percentile horsepower
 EXPORT
 COMMIT WHEN group.#count >= $nb_cars"
run
check_equal '1,946,1262598,278.167,552,313,140,553' "$(tail_ 1 p1)"

reset
start
add_123
add_node a1 "FROM test/123 SELECT AND b EXPORT COMMIT WHEN selected.#count = 1"
add_node a2 "FROM test/123 SELECT AND b EXPORT COMMIT WHEN selected.#count = 2"
add_node a3 "FROM test/123 SELECT AND b EXPORT COMMIT WHEN selected.#count = 3"
add_node o1 "FROM test/123 SELECT OR (not b) AS not_b EXPORT COMMIT WHEN selected.#count = 1"
add_node o2 "FROM test/123 SELECT OR (not b) AS not_b EXPORT COMMIT WHEN selected.#count = 2"
add_node o3 "FROM test/123 SELECT OR (not b) AS not_b EXPORT COMMIT WHEN selected.#count = 3"
run
check_equal 'true' "$(tail_ 1 a1)"
check_equal 'true' "$(tail_ 1 a2)"
check_equal 'false' "$(tail_ 1 a3)"
check_equal 'false' "$(tail_ 1 o1)"
check_equal 'false' "$(tail_ 1 o2)"
check_equal 'true' "$(tail_ 1 o3)"

# Check stateful functions in where clauses
reset
start
add_123
add_node n "SELECT n FROM test/123 WHERE lag n = 2 EXPORT"
run
check_equal '3' "$(tail_ 1 n)"
