#!/bin/sh

set -e
top_srcdir=$(dirname $0)"/../.."
. $top_srcdir/src/tests/funcs.sh

expected_tests=1

# Notice in the test above we wrap some_nullable_thing into a coalesce
# because ramen does not handle export of NULL values yet.

start
add_123
add_node p1 \
'FROM test/n123 SELECT
   CASE WHEN n > 2 THEN "hi"
        WHEN n < 2 THEN "lo"
        ELSE "meh"
   END AS bigness,
   CASE WHEN n = 1 THEN "one"
        ELSE "more"
   END AS literal,
   CASE WHEN n = 3 THEN 9999999999999999999
        WHEN n = 1 THEN 1
        ELSE 2
   END AS some_u64,
   CASE WHEN name = "one" THEN 6
        ELSE 666
   END AS some_nullable_thing,
   IF (n = 1, -1, -2) AS minus_smth,
   COALESCE(name,"three") AS real_name
 EXPORT'
run
check_equal '"lo","one",1,6,-1,"one"
"meh","more",2,666,-2,"two"
"hi","more",9999999999999999999,NULL,-2,"three"' "$(tail_ $nb_123 3 p1)"
