#!/bin/sh

set -e
top_srcdir=$(dirname $0)"/../.."
. $top_srcdir/src/tests/funcs.sh

expected_tests=2

start
add_123
add_node n \
"FROM test/n123
 SELECT SUM n
 COMMIT BEFORE sum_n > 4
 EXPORT"
run
check_equal '3' "$(tail_ $nb_123 1 n)"

reset
start
add_cars
add_node count_cars \
"FROM test/cars
 SELECT manufacturer, SUM 1 as nb_models
 COMMIT BEFORE out.manufacturer != COALESCE(group.previous.manufacturer, out.manufacturer)
 EXPORT"
run
# Note: we won't have "Volvo" at the end since it will never be commited:
check_equal '"aston martin",8
"Audi",51
"Bentley",8
"BMW",667
"FCA Italy",5
"FCA US LLC",250
"Ferrari",48
"FOMOCO",402
"GM",417
"Honda",371
"Hyundai",145
"Jaguar Land Rover L",76
"Kia",172
"Lamborghini",8
"Lotus",10
"Maserati",28
"MAZDA",88
"McLaren Automotive ",5
"Mercedes-Benz",224
"Mitsubishi Motors Co",39
"Nissan",416
"Porsche",102
"Rolls-Royce",13
"Roush",12
"Subaru",82
"Tesla",22
"Toyota",503
"Volkswagen",32
"Volkswagen Group of",284' "$(tail_ 29 29 count_cars)"
