#!/bin/sh

set -e
top_srcdir=$(dirname $0)"/../.."
. $top_srcdir/src/tests/funcs.sh

expected_tests=1

start
add_cars
add_node p1 \
"FROM test/cars SELECT
   first horsepower as first_1,
   max(min horsepower) as first_2,
   min(max horsepower) as first_3,
   -- Private field:
   COALESCE(CO2, 300) / horsepower as _co2_per_hp,
   -- We can use out fields in stateful functions:
   90th percentile _co2_per_hp,
   99th percentile globally _co2_per_hp
 EXPORT
 COMMIT WHEN group.#count >= $nb_cars"
run
check_equal '552,552,552,1.77402298851,2.71705617978' "$(tail_ 1 1 p1)"
