#!/bin/sh

set -e
top_srcdir=$(dirname $0)"/../.."
. $top_srcdir/src/tests/funcs.sh

expected_tests=1

start
add_123
add_node n "FROM test/n123 SELECT n, lag n AS lag1, lag (2, n) AS lag2 EXPORT"
run

check_equal '1,1,1
2,1,1
3,2,1' "$(tail_ $nb_123 3 n)"
