#!/bin/sh

set -e
top_srcdir=$(dirname $0)"/../.."
. $top_srcdir/src/tests/funcs.sh

expected_tests=1

start
add_func s1 "YIELD sequence(1,3) AS n EVERY 0.01 SECONDS"
add_func s2 "YIELD sequence(2,3) AS n EVERY 0.02 SECONDS"
add_func s3 "YIELD sequence(3,3) AS n EVERY 9999 SECONDS"
add_func m \
"FROM test/s1, test/s2, test/s3
 MERGE ON n TIMEOUT AFTER 0.1 SECOND
 SELECT n
 WHERE in.#count < 7
 EXPORT"
run
check_equal '1
2
3
4
5
7' "$(tail_ 6 6 m)"
