#!/bin/sh

set -e
top_srcdir=$(dirname $0)"/../.."
. $top_srcdir/src/tests/funcs.sh

expected_tests=2

# Tumbling windows:

start
add_func n1 "YIELD sequence as seq"
add_func n2 "
  SELECT first seq, last seq, group.#count as count, sum(1) as alt_count
  FROM test/n1
  WHERE seq < 30
  EXPORT
  COMMIT WHEN group.#count=10
"
run

check_equal '0,9,10,10
10,19,10,10
20,29,10,10' "$(tail_ 3 3 n2)"

# Sliding windows:

reset

start
add_func n1 "YIELD sequence as seq"
add_func n2 "
  SELECT first seq, last seq, group.#count as count, sum(1) as alt_count
  FROM test/n1
  WHERE seq < 14
  EXPORT
  COMMIT AND SLIDE 1 WHEN group.#count=10
" n1
run

check_equal '0,9,10,10
1,10,10,10
2,11,10,10
3,12,10,10
4,13,10,10' "$(tail_ 5 5 n2)"
