#!/bin/sh

set -e
top_srcdir=$(dirname $0)"/../.."
. $top_srcdir/src/tests/funcs.sh

expected_tests=1

start
add_earthquakes
add_func p \
"FROM test/earthquakes
 SORT LAST $((nb_earthquakes-4)) BY -n, year
 SELECT year
 EXPORT"
run
check_equal '2010
1968
1938
1957
1971' "$(tail_ 5 5 p)"
