#!/bin/sh

set -e
top_srcdir=$(dirname $0)"/../.."
. $top_srcdir/src/tests/funcs.sh

expected_tests=1

start
add_accounts
add_node n "
  FROM test/accounts
  SELECT name, sum amount
  TOP 3 BY sum amount WHEN in.#count >= $nb_accounts
  GROUP BY name
  EXPORT"
run

check_equal '"Joe",985
"John",587
"Willy",950' \
  "$(tail_ 3 n | sort)"
