#!/bin/sh

set -e
top_srcdir=$(dirname $0)"/../.."
. $top_srcdir/src/tests/funcs.sh

expected_tests=2

start
# Note: "," must not be the CSV separator!
add_func recv "RECEIVE SEPARATOR \"_\" (line string not null)"
add_func splitter "FROM test/recv SELECT split(\" \", line) AS word"

# Method 1: send the new count each time it changes

add_func counter1 "FROM test/splitter WHERE word <> \"\"
  SELECT group.#count AS count, lower(word) AS word
  GROUP BY word
  COMMIT AND KEEP ALL WHEN true
	EXPORT"

# Method 2: send all counts only when the word "END" is seen

add_func counter2 "FROM test/splitter WHERE word <> \"\"
  SELECT group.#count AS count, lower(word) AS word
  GROUP BY word
  COMMIT WHEN in.word = \"END\"
  EXPORT"

run
upload balade.txt recv
sleep 1 # Make sure we start by the above text
upload end.txt recv

check_equal '15,"nous"' \
  "$(tail_ 240 240 counter1 | sort -nr | head -1)"

check_equal '15,"nous"
8,"de"
5,"ne"
4,"mais"
4,"la"
4,"et"
3,"vueille"' \
  "$(tail_ 61 61 counter2 | sort -nr | head -7)"
