#!/bin/sh

set -e
top_srcdir=$(dirname $0)"/../.."
. $top_srcdir/src/tests/funcs.sh

expected_tests=4

start
add_func bla "YIELD \"pas glop\" AS s"
add_func n "FROM test/bla SELECT split(\" \", s) AS s1, \"glop\" AS s2 EXPORT"
run

check_equal '"glop","glop"
"pas","glop"' \
  "$(tail_ 2 2 n | sort)"

reset

start
add_func bla "YIELD \"foo bar\" AS s1, \"pas glop\" AS s2"
add_func n "FROM test/bla SELECT split(\" \", s1) AS s1, split(\" \", s2) AS s2 EXPORT"
run

check_equal '"bar","glop"
"bar","pas"
"foo","glop"
"foo","pas"' \
  "$(tail_ 4 4 n | sort)"

reset

# Now with some surrounding functions:

start
add_func bla "YIELD \"pas glop\" AS s"
add_func n "
  FROM test/bla
  SELECT split(\" \", s) || \" glop\" AS s1,
         \"pas \" || split(\" \", s) AS s2 EXPORT" bla
run

check_equal '"glop glop","pas glop"
"glop glop","pas pas"
"pas glop","pas glop"
"pas glop","pas pas"' \
  "$(tail_ 4 4 n | sort)"

reset

# Now with embedded functions:

start
add_func bla "YIELD \"glop\" AS s"
add_func n "FROM test/bla SELECT \"pas \" || split(\" \", s || \" glop\") AS s1 EXPORT"
run

check_equal '"pas glop"
"pas glop"' \
  "$(tail_ 2 2 n | sort)"
