let json_content_type = "application/json"
let dot_content_type = "text/dot"
let text_content_type = "text/plain"
let html_content_type = "text/html"
let css_content_type = "text/css"
let js_content_type = "application/javascript"
let ocaml_marshal_type = "application/marshaled.ocaml"

let in_tuple_count_metric = "in_tuple_count"
let out_tuple_count_metric = "out_tuple_count"
let cpu_time_metric = "cpu_time"
let ram_usage_metric = "ram_usage"
