#!/bin/sh

name=$1
shift

curl "$@" \
  -X PUT \
  -d '{
    "operation":
      "read csv file \"100k.csv\" separator "\t" (
        poller string not null,
        capture_begin u64 not null,
        capture_end u64 not null
      )"
  }' \
  -H 'Content-Type: application/json' http://localhost:29380/node/$name
