#!/bin/sh

set -e

cd /root/ramen

while true ; do
  echo
  echo "1) Build " $(grep ^VERSION Makefile)
  echo "2) Pull"
  echo "3) Checkout a particular tag/sha1"
  echo "4) Run a shell"
  echo "5) Exit"
  echo -n "Choice: "
  read REPLY

  case "$REPLY" in
    (1)
      echo "Cleaning previous deb files..."
      rm -f ramen.*.deb ramen.*.tgz

      opam install --verbose --yes --deps-only ramen
      make deb tarball

      deb_file=$(ls -1 ramen.*.deb)
      tgz_file=$(ls -1 ramen.*.tgz)

      echo "Done. Get your file(s) with:"
      echo "docker cp <container id>:/root/ramen/$deb_file ."
      echo "docker cp <container id>:/root/ramen/$tgz_file ."
      echo
      ;;
    (2)
      echo "Updating the source tree"
      git checkout master && git pull && ./configure
      ;;
    (3)
      echo -n "What version: "
      read REPLY
      if test -n "$REPLY" ; then
        echo "Checking out $REPLY"
        git checkout "$REPLY" || true
      else
        echo "never mind."
      fi
      ;;
    (4)
      echo "Running bash. Enter ^D when done to return to this menu."
      /bin/bash
      ;;
    (5)
      exit
      ;;
    (*)
      echo "Redo from start?"
      ;;
  esac
done
