# FROM ADDED BY MAKEFILE
# vim: ft=dockerfile

# Do not install recommends
RUN echo 'APT::Install-Recommends "0";' > \
      /etc/apt/apt.conf.d/no_recommends

# Install a few things
RUN apt-get --yes update && \
    DEBIAN_FRONTEND=noninteractive \
    apt-get --yes install \
      aspcud \
      binutils \
      bzip2 \
      ca-certificates \
      cmake \
      coreutils \
      g++ \
      git \
      libsasl2-dev \
      libsodium-dev \
      librdkafka-dev \
      libssl-dev \
      libz-dev \
      libzmq5-dev \
      m4 \
      make \
      ocaml-nox \
      patch \
      php-cli \
      rsync \
      sudo \
      unzip \
      vim-nox \
      wget

COPY install-opam.sh /tmp
RUN echo | /tmp/install-opam.sh

RUN /usr/local/bin/opam init --no-setup --disable-sandboxing
RUN /usr/local/bin/opam update --yes
RUN opam switch install --yes ramen.BER 4.07.1+BER

# Environment
ENV OPAM_SWITCH_PREFIX=/root/.opam/ramen.BER
ENV CAML_LD_LIBRARY_PATH=/root/.opam/ramen.BER/lib/stublibs:/root/.opam/ramen.BER/lib/ocaml/stublibs:/root/.opam/ramen.BER/lib/ocaml
ENV OCAML_TOPLEVEL_PATH=/root/.opam/ramen.BER/lib/toplevel
ENV MANPATH=:/root/.opam/ramen.BER/man
ENV PATH=/root/.opam/ramen.BER/bin:/root/.gem/ruby/2.5.0/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ENV RAMEN_LIBS=/root/project/bundle

RUN opam update
RUN opam install --yes depext
RUN opam depext --noninteractive \
      conf-gsl conf-blas conf-lapack conf-pkg-config sqlite3
RUN opam repo add --set-default ocalme \
      git://github.com/rixed/ocalme-opam-repository.git
RUN opam repo priority ocalme 1

# One need master to compile with BER (fixed in next major release)
RUN opam pin add batteries --dev-repo --no-action

# Install all ramen dependencies using opam
RUN opam update
RUN opam install --yes inotify qtest

COPY z3 /usr/bin/

# Install all ramen dependencies using opam
RUN cd /root && \
    git clone https://github.com/rixed/ramen.git && \
    git clone https://github.com/PerformanceVision/ramen-configurator.git && \
    cd ramen && \
    git checkout v@PACKAGE_VERSION@

RUN opam pin --no-action add ramen /root/ramen
RUN opam install --yes --deps-only ramen
RUN cd /root/ramen && ./configure

COPY build-deb /

LABEL maintainer="rixed-docker@happyleptic.org"

ENTRYPOINT ["/build-deb"]
