# vim: ft=dockerfile
FROM rixed/ramen-dev-base

# Install a few more things that circleci do not need but than a human
# might want
RUN DEBIAN_FRONTEND=noninteractive \
    apt-get --yes install \
      cscope \
      emacs-nox \
      less \
      strace \
      valgrind \
      vim-nox

RUN opam install --yes down ocp-index odig odoc

ENTRYPOINT ["/bin/bash"]
