# We cannot start from rixed/ramen:dev since it would prevent squashing
FROM debian:buster-slim

# Do not install recommends:
RUN echo 'APT::Install-Recommends "0";' > \
      /etc/apt/apt.conf.d/no_recommends

# Install a few things
RUN apt-get --yes update && \
    DEBIAN_FRONTEND=noninteractive \
      apt-get --yes upgrade && \
    DEBIAN_FRONTEND=noninteractive \
      apt-get --yes install \
        curl \
        g++ \
        gcc \
        iproute2 \
        iputils-ping \
        libblas-dev \
        liblapack-dev \
        liblmdb-dev \
        librdkafka-dev \
        libsasl2-dev \
        libsodium-dev \
        libsqlite3-0 \
        libssl-dev \
        libz-dev \
        libzmq5-dev \
        procps \
        net-tools \
        ssh-client \
        unzip

# Install wireguard
RUN echo "deb http://deb.debian.org/debian/ unstable main" > /etc/apt/sources.list.d/unstable.list
RUN printf 'Package: *\nPin: release a=unstable\nPin-Priority: 90\n' > /etc/apt/preferences.d/limit-unstable
RUN apt-get --yes update
RUN DEBIAN_FRONTEND=noninteractive \
      apt-get --yes install wireguard
COPY wgnet0.conf.tmpl /etc/wireguard

# Install boringtun from the last published release:
COPY boringtun_0.2.0+1903281651-bf310c7~buster_amd64.deb /tmp
RUN dpkg -i /tmp/boringtun_0.2.0+1903281651-bf310c7~buster_amd64.deb && \
    rm /tmp/boringtun_0.2.0+1903281651-bf310c7~buster_amd64.deb

RUN echo update
# Install ramen
COPY ramen.@PACKAGE_VERSION@.deb /tmp
RUN dpkg -i /tmp/ramen.@PACKAGE_VERSION@.deb && \
    rm /tmp/ramen.@PACKAGE_VERSION@.deb
# And z3
COPY z3 /usr/bin/z3

# Environment
ENV RAMEN_DIR=/ramen
# Override for multi-site deployment:
ENV RAMEN_CONFSERVER=127.0.0.1:29340

# Command to be run:
WORKDIR /ramen
COPY start /
ENTRYPOINT ["/start"]

# Collectd:
EXPOSE 25826/UDP
# Fprobe:
EXPOSE 2055/UDP
# Confserver (insecure, only local and VPN)
EXPOSE 29340/TCP
# Confserver (secure)
EXPOSE 29341/TCP
# Tunneld
EXPOSE 29329/TCP
# Httpd
EXPOSE 29380/TCP
# Graphite sink
EXPOSE 2003/TCP

LABEL maintainer="rixed@happyleptic.org"
