# FROM ADDED BY MAKEFILE
# vim: ft=dockerfile expandtab

# Do not install recommends and remove unused deps automatically:
RUN echo 'APT::Install-Recommends "0";' > \
      /etc/apt/apt.conf.d/no_recommends
RUN echo 'APT::Get::AutomaticRemove "1";' > \
      /etc/apt/apt.conf.d/no_recommends

# Install a few things
RUN apt-get --yes update && \
    DEBIAN_FRONTEND=noninteractive \
    apt-get --yes install \
      aspcud \
      binutils \
      bzip2 \
      ca-certificates \
      cmake \
      coreutils \
      cucumber \
      curl \
      emacs-nox \
      fakeroot \
      fuse \
      g++ \
      git \
      iputils-ping \
      imagemagick \
      less \
      librdkafka-dev \
      libsasl2-dev \
      libsodium-dev \
      libssl-dev \
      libz-dev \
      libzmq5-dev \
      manpages \
      manpages-dev \
      m4 \
      make \
      ocaml-nox \
      patch \
      php-cli \
      qt5-default \
      rsync \
      ruby-rspec \
      socat \
      sqlite3 \
      strace \
      sudo \
      unzip \
      valgrind \
      vim-nox \
      wget \
      xauth

COPY install-opam.sh /tmp
RUN echo | /tmp/install-opam.sh

RUN /usr/local/bin/opam init --no-setup --disable-sandboxing
RUN /usr/local/bin/opam update --yes
RUN opam switch install --yes ramen.BER 4.07.1+BER

# Environment
ENV OPAM_SWITCH_PREFIX=/root/.opam/ramen.BER
ENV CAML_LD_LIBRARY_PATH=/root/.opam/ramen.BER/lib/stublibs:/root/.opam/ramen.BER/lib/ocaml/stublibs:/root/.opam/ramen.BER/lib/ocaml
ENV OCAML_TOPLEVEL_PATH=/root/.opam/ramen.BER/lib/toplevel
ENV MANPATH=:/root/.opam/ramen.BER/man
ENV PATH=/root/.opam/ramen.BER/bin:/root/.gem/ruby/2.5.0/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ENV RAMEN_LIBS=/root/ramen/bundle

# Install linuxdeploy.AppImage and its qt plugin:
RUN wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage -O /usr/bin/linuxdeploy-x86_64.AppImage
RUN chmod a+x /usr/bin/linuxdeploy-x86_64.AppImage
RUN wget https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage -O /usr/bin/linuxdeploy-plugin-qt-x86_64.AppImage
RUN chmod a+x /usr/bin/linuxdeploy-plugin-qt-x86_64.AppImage

# qt5charts is not packaged in stretch for some reason, but easy to
# build from sources:
COPY getqt5charts /tmp
RUN /tmp/getqt5charts

RUN opam update
RUN opam install --yes depext
RUN opam depext --noninteractive \
      conf-gsl conf-blas conf-lapack conf-pkg-config sqlite3
RUN opam repo add --set-default ocalme \
      git://github.com/rixed/ocalme-opam-repository.git
RUN opam repo priority ocalme 1

# One need master to compile with BER (fixed in next major release)
RUN opam pin add batteries --dev-repo --no-action

# Install all ramen dependencies using opam
RUN opam install --yes inotify qtest

# For convenience:
RUN opam install --yes down ocp-index odig odoc

# Now install z3 from source (as we need both executable and libs):
RUN cd /root && \
    git clone https://github.com/Z3Prover/z3.git && \
    cd z3 && \
    git checkout z3-4.8.6 && \
    DEBIAN_FRONTEND=noninteractive apt-get install --yes python && \
    python scripts/mk_make.py && \
    cd build && \
    make && \
    make install && \
    DEBIAN_FRONTEND=noninteractive apt-get purge --yes python

# Refresh opam packages before installing ramen deps
RUN echo "Update opam packages for latest dessser" && \
    opam update

ARG RAMEN_DIR=@srcdir@
ADD RAMEN_DIR /tmp/ramen
RUN cd /root &&
    git clone /tmp/ramen
    rm -rf /tmp/ramen

# Install all ramen dependencies using opam
RUN cd /root && \
    git clone https://github.com/PerformanceVision/ramen-configurator.git && \
    cd ramen && \
    git checkout v@PACKAGE_VERSION@ || git checkout master && \
    ./configure && \
    opam install --yes --deps-only .

# Perform a first build to get the submodule compiled already which save a lot
# of time later.
RUN cd /root/ramen && make || true

COPY builder /

LABEL maintainer="rixed-docker@happyleptic.org"

ENTRYPOINT ["/builder"]
