# vim: ft=dockerfile
FROM debian:buster-slim

# Do not install recommends
RUN echo 'APT::Install-Recommends "0";' > \
      /etc/apt/apt.conf.d/no_recommends

# Install a few things
RUN apt-get --yes update && \
    apt-get --yes dist-upgrade && \
    DEBIAN_FRONTEND=noninteractive \
    apt-get --yes install \
      aspcud \
      bzip2 \
      ca-certificates \
      cmake \
      coreutils \
      curl \
      g++ \
      git \
      libsasl2-dev \
      libsodium-dev \
      libssl-dev \
      libzmq5-dev \
      m4 \
      make \
      ocaml-nox \
      patch \
      rsync \
      ruby \
      socat \
      sqlite3 \
      ssh \
      sudo \
      unzip \
      wget

RUN wget https://raw.github.com/ocaml/opam/master/shell/opam_installer.sh -O - | \
    sh -s /usr/local/bin

RUN /usr/local/bin/opam init --comp 4.06.1+flambda --no-setup

# Environment
ENV CAML_LD_LIBRARY_PATH=/root/.opam/4.06.1+flambda/lib/stublibs \
    PATH=/root/.opam/4.06.1+flambda/bin:/root/.gem/ruby/2.5.0/bin/:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/bin \
    RAMEN_LIBS=/root/project/bundle \
    TERM=dumb

RUN echo 'Update dependency on Binocle/PPP (-> v0.10.0, v.2.8.0)'

RUN opam update && \
    opam install depext && \
    opam depext --noninteractive \
      conf-gsl conf-blas conf-lapack conf-pkg-config sqlite3 && \
    opam repo add --priority=1 ocalme \
      git://github.com/rixed/ocalme-opam-repository.git

# Temp before next release of ramen with new deps:
RUN opam install zmq sodium

# Install all ramen dependencies using opam
RUN opam install inotify qtest && \
    opam install --deps-only ramen

# Install Cucumber
RUN gem install --user-install cucumber rspec rspec_junit_formatter minitest-ci

COPY z3 /usr/bin/

LABEL maintainer="rixed-docker@happyleptic.org"

ENTRYPOINT ["/bin/bash"]
