#!/bin/sh

# Work around https://github.com/ryanrhymes/owl/issues/116
mkdir -p /root/.owl/dataset /root/.owl/zoo

if test -x /usr/sbin/collectd ; then
  /usr/sbin/collectd -C /etc/collectd/collectd.conf
fi
if test -x /usr/sbin/fprobe ; then
  /usr/sbin/fprobe 127.0.0.1:2055
fi

exec ramen start $@
