#!/bin/sh

set -e
top_srcdir=$(dirname $0)"/.."
. $top_srcdir/tests/funcs.sh

expected_tests=7

start
add_cars
add_node p1 \
"SELECT
   min horsepower,
   max horsepower,
   sum u32(horsepower) as sum_horsepower,
   first horsepower,
   last horsepower,
   10th percentile of horsepower,
   95th percentile of horsepower
 EXPORT
 COMMIT AND FLUSH WHEN group.#count >= $nb_cars" cars
run
check_equal '1,946,1262598,552,313,141,553' "$(tail_ 1 p1)"

reset
start
add_123
add_node a1 "SELECT AND of b EXPORT COMMIT AND FLUSH WHEN selected.#count = 1" 123
add_node a2 "SELECT AND of b EXPORT COMMIT AND FLUSH WHEN selected.#count = 2" 123
add_node a3 "SELECT AND of b EXPORT COMMIT AND FLUSH WHEN selected.#count = 3" 123
add_node o1 "SELECT OR of (not b) AS not_b EXPORT COMMIT AND FLUSH WHEN selected.#count = 1" 123
add_node o2 "SELECT OR of (not b) AS not_b EXPORT COMMIT AND FLUSH WHEN selected.#count = 2" 123
add_node o3 "SELECT OR of (not b) AS not_b EXPORT COMMIT AND FLUSH WHEN selected.#count = 3" 123
run
check_equal 'true' "$(tail_ 1 a1)"
check_equal 'true' "$(tail_ 1 a2)"
check_equal 'false' "$(tail_ 1 a3)"
check_equal 'false' "$(tail_ 1 o1)"
check_equal 'false' "$(tail_ 1 o2)"
check_equal 'true' "$(tail_ 1 o3)"
