#!/bin/sh

set -e
top_srcdir=$(dirname $0)"/.."
. $top_srcdir/tests/funcs.sh

start
add_123
add_node n "SELECT 10*n AS ten_n, in.#count AS count WHERE n=3 EXPORT" 123
run

check_equal '30,3' "$(tail_ 1 n)"
