// vim:filetype=asciidoc expandtab spell spelllang=en ts=2 sw=2
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Alerting
:toc:
:icons:
:lang: en
:encoding: utf-8

== What is alert management?

Once Ramen (or any other monitoring system) has detected a problem and has
issued a notification, what to do with it?

Naïvely, one could plug directly this notification signal into an alerting box
(complete with a red flashing light and a loud siren) and call it a day.

There are many issues with this approach though:

First, you must make sure that at any time, enough engineers will be sitting
close to the alerting box and that one of them will handle the alert. But
paying engineers to sit close to a box (or to stare at some dashboard) is not
efficient. Also, disturbing everyone with a broadcasted alerting signal (the
siren and flashing lights) is also spoiling a lot of engineering time.

It is therefore much better to disturb just the one person who is supposed to
care for that alert, which imply that you know which group of person can handle
each type of alert, and also that you know how to reach one dedicated person
(for instance using his individual email, phone or pager).

Second, you want the sirens to shut down, the lights to stop flashing and the
pager to stop paging once that person started to work on the incident in order
not to disturb him. So you need the concept of an acknowledgment, to silence
the alert until it stops firing.

But then arise other issues.
First, what to do if the alerting box fails to reach the on-call engineer?
Obviously, after a while, we should cascade the alert to someone else. We must
then have ordered sets of on-callers.

Also, what if the alert stops/starts firing repeatedly? Those flapping alerts
should be dealt with hystereses.

Also, how to we balance the load of being on-call amongst several people?
What happens when the on-caller changes while an alert is going on?
How to transfers the knowledge of the recent incidents with the next shift of
on-call engineers?

As you can see, the complexity grows quickly, thus the need for a dedicated
program managing this workflow: the alerter.

== Data Model

Let's start from the actual static configuration:

[source,json]
----
{
  "oncallers": [
    {
      "name": "John Doe",
      "contacts": [
        { "SMS": "+06987654321" }
        { "Email": { "to": "john.doe@mail.com", "cc": "tech@mail.com" } },
      ]
    }, {
      "name": "Bill Yang",
      "contacts": [
        { "SMS": "+06123456789" }
      ]
    }, {
      "name": "Everybody",
      "contacts": [
        { "SysLog": null }
      ]
    }
  ],

  "teams": [
    {
      "name": "firefighters",
      "members": [
        "John Doe",
        "Bill Yang",
        "Everybody"
      ],
      "escalations": [
        {
          "importance": 0,
          "steps": [
            { "timeout": 350.0, "victims": [ 0 ] },
            { "timeout": 350.0, "victims": [ 0, 1 ] }
          ]
        }
      ],
      "inhibitions": []
    }
  ],

  "schedule": [
    {
      "rank": 0,
      "from": 1513701000,
      "oncaller": "John Doe"
    }, {
      "rank": 1,
      "from": 0,
      "oncaller": "Everybody"
    }, {
      "rank": 0,
      "from": 1513787000,
      "oncaller": "Bill Yang"
    }
  ]
}
----

We have three blocks on the above configuration:

a list on oncallers (physical persons such as "John Doe" and "Bill Yang" or
aliases such as "Everybody"), with for each a list of means to contact them
(which could be email, SMS, syslog, console or sqlite, each of which come
with its own set of parameters).

Then you have the teams definition, with a single team named "firefighters"
in this example. Beside the list of oncallers, the team also have a
configuration for how and when to escalate an alert when it's not
acknowledged (a list with a timeout and who to contact, the integers in the
+victims+ array corresponding to the +rank+ in the on-call schedule (see
bellow).

Then, the on-call schedule. It is merely composed of an unordered list of
single person shifts. The +from+ field is the timestamp of the beginning of
the shift, +oncaller+ is the person assigned this shift, and +rank+ tells the
alerter if this person is supposed to be first, second, etc on-call
(corresponding to the integer numbers used in the +victim+ field of the
escalation, but typically the +rank+ 0 will be contacted first, then rank +1+
will be contacted if +0+ fails to acknowledge the alert, and so on.
