top_srcdir = ../

all:
	@true # Avoids "nothing to be done for ..." message

doc: \
	tutorial_network_monitoring.html tutorial_counting_words.html \
	manual.html roadmap.html alerter.html

tutorial_network_monitoring.html: tutorial_group_by.svg sample_chart1.svg

check-spec:
	@true

clean-spec:
	@true

distclean-spec:
	$(RM) tutorial.html manual.html roadmap.html

install-spec:
	@true

include $(top_srcdir)/make.common
