top_srcdir = ../

all:

clean-spec:

distclean-spec:
	$(RM) tutorial.html

install-spec:

publish: tutorial.html
	scp tutorial.html pim:public_html/ramen_tutorial.html
	
include $(top_srcdir)/make.common
