top_srcdir = ../

all:
	@true # Avoids "nothing to be done for ..." message

doc: tutorial.html manual.html roadmap.html

check-spec:
	@true

clean-spec:
	@true

distclean-spec:
	$(RM) tutorial.html manual.html roadmap.html

install-spec:
	@true

include $(top_srcdir)/make.common
