(* Helpers for code generated by the Dessser OCaml backend *)

let pointer_of_tx tx =
  let b = RingBuf.read_raw_tx tx in
  DessserOCamlBackEndHelpers.Pointer.of_bytes b 0 (Bytes.length b)

(* Once a tuple has been serialized into a data_ptr, the pointer buffer must
 * then be copied into the TX content.
 * FIXME: other dessser backends are supposed to save us from this ineptitude *)
let blit_into_tx tx ptr =
  let offs = 4 in (* The message header has been written already *)
  RingBuf.write_raw_tx tx offs ptr.DessserOCamlBackEndHelpers.Pointer.bytes

(* Dessser has no type variables and cannot build pairs (or tuples) so we need
 * those very explicit helpers: *)

let make_float_pair (v1 : float) (v2 : float) =
  v1, v2

let make_string_pair (v1 : string) (v2 : string) =
  v1, v2

let make_factor_value (v1 : string) (v2 : RamenTypes.value) =
  v1, v2

let make_extractors_vector slist =
  Array.of_list slist
