(* Generated by Makefile - edition is futile *)
let incdirs = [
  "batteries" ;
  "binocle" ;
  "bytes" ;
  "inotify" ;
  "lacaml" ;
  "lwt" ;
  "lwt_ppx" ;
  "num" ;
  "ocaml" ;
  "parsercombinator" ;
  "ppp" ;
  "ramen" ;
  "result" ;
  "stdint" ;
  "ocaml/threads" ;
]
let objfiles = [
  "ocaml/unix.cmxa" ;
  "ocaml/threads/threads.cmxa" ;
  "ocaml/bigarray.cmxa" ;
  "result/result.cmxa" ;
  "lwt/lwt.cmxa" ;
  "lwt/lwt_log.cmxa" ;
  "lwt/lwt_unix.cmxa" ;
  "ocaml/nums.cmxa" ;
  "ocaml/str.cmxa" ;
  "batteries/batteries.cmxa" ;
  "stdint/stdint.cmxa" ;
  "parsercombinator/parsercombinator.cmxa" ;
  "inotify/inotify.cmxa" ;
  "inotify/inotify-lwt.cmxa" ;
  "binocle/Binocle.cmxa" ;
  "lacaml/lacaml.cmxa" ;
  "ppp/PPP.cmxa" ;
  "ppp/PPP-unix.cmxa" ;
  "ramen/codegen.cmxa" ;
]
